spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://safetycubetst.aircraft-sita.aero/authorization
  datasource:
    url: jdbc:mariadb://localhost:3306/safetycube  # Replace with your MariaDB URL and database name
    driverClassName: org.mariadb.jdbc.Driver
    username: user  # Replace with your MariaDB username
    password: user_password  # Replace with your MariaDB password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: user_password
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 60000
